Allow extra volumes and volumeMounts in the weaviate StatefulSet
weaviate/weaviate-helm pull request #160
Opened 2023-08-03 17:58 UTC by kristofvc

For a project we keep our secrets in AWS, and parse them as kubernetes secrets with the secret store CSI driver (https://secrets-store-csi-driver.sigs.k8s.io). For this to actually work you need a volume and volumeMount that use this driver to make sure the secrets are fetched from AWS, en the secret resource is created. 
Since we want to use an AWS stored secret for the AUTHENTICATION_APIKEY_ALLOWED_KEYS, env var, we thus need a pod with the mentioned volume and volumeMount. 

We now circumvent this issue by just spinning up a pod which is indefinitely sleeping, but it would be cleaner if we could just add it to the weaviate Statefulset. 

So hereby a PR to add functionality to allow any number of extra volumes or volumeMounts.

2023-08-04 07:29 UTC, kristofvc commented
I agree with the CLA

2023-09-05 13:37 UTC, StefanBogdan approved these changes

2023-09-05 13:38 UTC, StefanBogdan requested changes
@kristofvc Can you add some unit tests?

2023-10-20 08:42 UTC, kristofvc commented
@StefanBogdan completely missed this message, not the biggest helm-connoisseur, but I'll have a look

2023-11-28 18:30 UTC, kristofvc commented
I've add some tests, is this enough?

2023-11-29 13:04 UTC, merged